name: check
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: setup uv
        uses: astral-sh/setup-uv@v5

      - name: check
        run: |
          uv run -- ruff format --check .
          uv run -- ruff check .
          uv run -- ty check .

      - name: test
        run: uv run -- pytest .
